### ISSUE TITLE
Create an Updated No-Frills Quick-Start Guide

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/deephaven-plugins#38]
It is a bit difficult to follow the absolutely bare minimum steps to get the `table-example` working in a `0.20.x` release.

Sample `$DEST/docker-compose.yml`:
```yaml
version: "3.4"

services:
  deephaven:
    image: ghcr.io/deephaven/server:0.20.0
    ports:
      - "10000:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g -Ddeephaven.jsPlugins.resourceBase=/data/js-plugins
```

Sample install:
```bash
npm install
npm run build
mkdir -p $DEST/data/js-plugins/table-example
cp -rf table-example/dist $DEST/table-example/
```

Sample `$DEST/data/js-plugins/manifest.json`:
```json
{
    "plugins": [
      { "name": "table-example", "version": "0.2.0", "main": "dist/index.js" }
    ]
}
```

The python snippet changes in 0.20+:
```python
from deephaven import empty_table
from deephaven.jcompat import j_hashmap 
t = empty_table(5).update("X=i").j_table.withAttributes(j_hashmap({"PluginName" : "table-example"}))
```
